post http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "description": "ok",
    "date": "2024-02-02",
    "specialist": "Dr doozer",
    "sickLeave": {"startDate": "2020-11-02", "endDate": "2020-02-03"},
    "employerName": "Eficode",
    "type": "OccupationalHealthcare"
}